<x-layouts::public title="Terms of Service">
    <article class="space-y-8">
        <header class="space-y-3">
            <p class="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700 dark:text-emerald-400">Legal</p>
            <h1 class="text-3xl font-semibold tracking-tight sm:text-4xl">Terms of Service</h1>
            <p class="text-zinc-600 dark:text-zinc-400">Effective {{ config('legal.effective_date') }}</p>
            <p class="max-w-3xl text-lg leading-8 text-zinc-700 dark:text-zinc-300">These terms govern business use of {{ config('app.name') }}, operated by {{ config('legal.operator_name') }}.</p>
        </header>

        <section class="space-y-3"><h2 class="text-xl font-semibold">1. Account authority</h2><p>You must provide accurate account information and protect your login credentials. If you create or administer a workspace, you confirm that you are authorized to act for that business and to invite its users.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">2. Customer data</h2><p>You retain responsibility for the customer, contact, lead, message, and other business data you enter or connect. You must have a lawful basis and all necessary notices or permissions to collect, use, message, import, and store that data. You instruct us to process it only to provide the service.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">3. Meta connections</h2><p>You may connect only Pages, accounts, forms, and business assets you are authorized to manage. Your use must comply with Meta's terms, developer policies, messaging rules, and applicable law. Permissions or API availability may change, and reconnecting or review may be required.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">4. Acceptable use</h2><p>You may not use the service to violate law or third-party rights, send spam or unlawful messages, upload malicious code, bypass access controls or plan limits, interfere with other tenants, probe the service without authorization, or collect sensitive information without appropriate authority and safeguards.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">5. Plans and availability</h2><p>Features and usage limits depend on the workspace plan. We may maintain, improve, or modify the service and may temporarily interrupt access for security, maintenance, provider outages, or events outside reasonable control. We will use reasonable efforts to protect continuity but do not promise uninterrupted operation.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">6. Suspension and termination</h2><p>We may restrict or suspend access when reasonably necessary to protect the service, other customers, or legal compliance, including for abuse, security risk, or material breach of these terms. You may request account or workspace deletion using the public <a href="{{ route('legal.data-deletion') }}" class="text-emerald-700 underline dark:text-emerald-400">data deletion process</a>.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">7. Intellectual property</h2><p>{{ config('legal.operator_name') }} and its licensors retain rights in the service, software, branding, and documentation. These terms give you a limited, non-exclusive right to use the service for your organization's internal business operations while your account is authorized.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">8. Disclaimers and responsibility</h2><p>The service is provided on an “as available” basis to the extent permitted by applicable law. OCR, reports, automations, imported data, and third-party integrations can be incomplete or inaccurate and must be reviewed before business decisions or communications. Neither party excludes liability that cannot lawfully be excluded.</p></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">9. Changes and contact</h2><p>We may update these terms as the service changes. Continued use after an updated effective date means acceptance of the revised terms where permitted by law. Questions can be sent to <a href="mailto:{{ config('legal.contact_email') }}" class="text-emerald-700 underline dark:text-emerald-400">{{ config('legal.contact_email') }}</a>.</p></section>
    </article>
</x-layouts::public>
